//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 05c
//  @ File Name : Building.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>

#include "Building.h"

using namespace std;

string Building::getAddress() {
    return address;
}

void Building::setAddress(string address) {
    this->address = address;
}

int Building::getSize() {
    return size;
}

void Building::setSize(int size) {
    this->size = size;
}

float Building::getMaintenanceCost() {
    return maintenanceCost;
}

void Building::setMaintenanceCost(float maintenanceCost) {
    this->maintenanceCost = maintenanceCost;
}

bool Building::getIsItAirConditioned() {
    return isItAirConditioned;
}

void Building::setIsItAirConditioned(bool isItAirConditioned) {
    this->isItAirConditioned = isItAirConditioned;
}

int Building::getNumberOfCashRegisters() {
    return numberOfCashRegisters;
}

void Building::setNumberOfCashRegisters(int numberOfCashRegisters) {
    this->numberOfCashRegisters = numberOfCashRegisters;
}

Building::Building(string address, int size, float maintenanceCost, bool isItAirConditioned, int numberOfCashRegisters) {
    setAddress(address);
    setSize(size);
    setMaintenanceCost(maintenanceCost);
    setIsItAirConditioned(isItAirConditioned);
    setNumberOfCashRegisters(numberOfCashRegisters);
}

Building::~Building() {}

void Building::payBills() {
    cout << "Paying bills..." << endl;
}

void Building::cleanBuilding() {
    cout << "Cleaning building..." << endl;
}

void Building::printBuilding() {
    cout << "Address: " << getAddress() << endl;
    cout << "Size: " << getSize() << endl;
    cout << "Maintenance cost: " << getMaintenanceCost() << endl;
    cout << "Is it air conditioned: " << getIsItAirConditioned() << endl;
    cout << "Number of cash registers: " << getNumberOfCashRegisters() << endl;
}
