//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03a
//  @ File Name : CareTaker.h
//  @ Date : 18.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_CARETAKER_H)
#define _CARETAKER_H

#include <string>
#include "Cat.h"

using namespace std;

class CareTaker {
public:
	void setName(string name);
	void setHeight(float height);
	void setAge(int age);
	void setHobby(string hobby);
	void setCanTakeCareOfCat(bool canTakeCareOfCat);
	string getName();
	float getHeight();
	int getAge();
	string getHobby();
	bool getCanTakeCareOfCat();
	CareTaker(string name, float height, int age, string hobby, bool canTakeCareOfCat);
	~CareTaker();
	void takeCareOfYourHobby();
	void goShopping();
private:
	string name;
	float height;
	int age;
	string hobby;
	bool canTakeCareOfCat;
};

#endif  //_CARETAKER_H
