//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03a
//  @ File Name : Cat.cpp
//  @ Date : 18.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>
#include "Cat.h"

void Cat::setName(string name) {
    this->name = name;
}

void Cat::setColor(string color) {
    this->color = color;
}

void Cat::setAge(int age) {
    this->age = age;
}

void Cat::setIsCatFed(bool canTakeCareOfCat, bool feedCat) {
    if((feedCat) && (canTakeCareOfCat)) {
        this->isCatFed = true;
    } else {
        this->isCatFed = false;
    }
}

void Cat::setIsCatPetted(bool canTakeCareOfCat, bool petCat) {
    if((petCat) && (canTakeCareOfCat)) {
        this->isCatPetted = true;
    } else {
        this->isCatPetted = false;
    }
}

string Cat::getName() {
    return name;
}

string Cat::getColor() {
    return color;
}

int Cat::getAge() {
    return age;
}

bool Cat::getIsCatFed() {
    return isCatFed;
}

bool Cat::getIsCatPetted() {
    return isCatPetted;
}

Cat::Cat(string name, string color, int age, bool isCatFed, bool isCatPetted) {
    setName(name);
    setColor(color);
    setAge(age);
    this->isCatFed = isCatFed;
    this->isCatPetted = isCatPetted;
}

Cat::~Cat() {}

void Cat::getPetted() {
    cout << name << " gets petted!" << endl;
}

void Cat::meow() {
    cout << name << " meows!" << endl;
}

void Cat::purr() {
    cout << name << " purrs!" << endl;
}
