//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03a
//  @ File Name : Cat.h
//  @ Date : 18.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_CAT_H)
#define _CAT_H

#include <string>

using namespace std;

class Cat {
public:
	string getName();
	void setName(string name);
	string getColor();
	void setColor(string color);
	int getAge();
	void setAge(int age);
	bool getIsCatFed();
	void setIsCatFed(bool canTakeCareOfCat, bool isCatFed);
	bool getIsCatPetted();
	void setIsCatPetted(bool canTakeCareOfCat, bool isCatPetted);
	Cat(string name, string color, int age, bool isCatFed, bool isCatPetted);
	~Cat();
	void getPetted();
	void meow();
	void purr();
private:
	string name;
	string color;
	int age;
	bool isCatFed;
	bool isCatPetted;
};

#endif  //_CAT_H
