//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03a
//  @ File Name : Kot.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_KOT_H)
#define _KOT_H

#include <string>
#include "Opiekun.h"


class Kot {
public:
	void setImie(std::string imie);
	void setKolor(std::string kolor);
	void setWiek(int wiek);
	void setPoglaskany(bool mozeZajacSieKotem, bool poglaskany);
	void setNajedzony(bool mozeZajacSieKotem, bool najedzony);
    std::string getImie();
    std::string getKolor();
	int getWiek();
	bool getPoglaskany();
	bool getNajedzony();
	Kot(std::string imie, std::string kolor, int wiek, bool poglskany, bool najedzony);
    ~Kot();
	void dajSiePoglskac(std::string imieOsoby);
	void zamiaucz();
	void zamrucz();
private:
    std::string imie;
    std::string kolor;
	int wiek;
	bool poglaskany;
	bool najedzony;
};

#endif  //_KOT_H
