//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03a
//  @ File Name : Opiekun.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_OPIEKUN_H)
#define _OPIEKUN_H

#include <string>
#include "Kot.h"

class Opiekun {
public:
	void setImie(std::string imie);
	void setWzrost(float wzrost);
	void setWiek(int wiek);
	void setHobby(std::string hobby);
	void setMozeZajacSieKotem(bool mozeZajacSieKotem);
    std::string getImie();
	float getWzrost();
	int getWiek();
    std::string getHobby();
	bool getMozeZajacSieKotem();
	Opiekun(std::string imie, float wzrost, int wiek, std::string hobby, bool mozeZajacSieKotem);
	~Opiekun();
	void zajmijSieSwoimHobby();
	void zrobZakupy();
private:
    std::string imie;
	float wzrost;
	int wiek;
    std::string hobby;
	bool mozeZajacSieKotem;
};

#endif  //_OPIEKUN_H
