//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.cpp
//  @ Date : 29.03.2023
//  @ Author : 
//
//


#include "Przedmiot.h"

void Przedmiot::setNazwa(string nazwa) {

}

void Przedmiot::setOpis(string opis) {

}

void Przedmiot::setPunktyEtcs(float punktyEtcs) {

}

void Przedmiot::setProwadzacy(string prowadzacy) {

}

void Przedmiot::setIloscGodzinPracyWlasnej(int iloscGodzinPracyWlasnej) {

}

string Przedmiot::getNazwa() {

}

string Przedmiot::getOpis() {

}

float Przedmiot::getPunktyEtcs() {

}

string Przedmiot::getProwadzacy() {

}

int Przedmiot::getIloscGodzinPracyWlasnej() {

}

void Przedmiot::Przedmiot(string nazwa, string opis, float punktyEtcs, string prowadzacy, int iloscGodzinPracyWlasnej) {

}

void Przedmiot::Przedmiot() {

}

void Przedmiot::wyswietlOpis() {

}

void Przedmiot::wyswietlProwadzacego() {

}

void Przedmiot::wyswietlIloscGodzinPracyWlasnej() {

}

