//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.h
//  @ Date : 29.03.2023
//  @ Author : 
//
//


#if !defined(_PRZEDMIOT_H)
#define _PRZEDMIOT_H


class Przedmiot {
public:
	void setNazwa(string nazwa);
	void setOpis(string opis);
	void setPunktyEtcs(float punktyEtcs);
	void setProwadzacy(string prowadzacy);
	void setIloscGodzinPracyWlasnej(int iloscGodzinPracyWlasnej);
	string getNazwa();
	string getOpis();
	float getPunktyEtcs();
	string getProwadzacy();
	int getIloscGodzinPracyWlasnej();
	void Przedmiot(string nazwa, string opis, float punktyEtcs, string prowadzacy, int iloscGodzinPracyWlasnej);
	void Przedmiot();
	void wyswietlOpis();
	void wyswietlProwadzacego();
	void wyswietlIloscGodzinPracyWlasnej();
private:
	string nazwa;
	string opis;
	float punktyEtcs;
	string prowadzacy;
	int iloscGodzinPracyWlasnej;
};

#endif  //_PRZEDMIOT_H
