//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03b
//  @ File Name : Przedmiot.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_PRZEDMIOT_H)
#define _PRZEDMIOT_H

#include <string>

class Przedmiot {
public:
	void setNazwa(std::string nazwa);
	void setOpis(std::string opis);
	void setPunktyEtcs(float punktyEtcs);
	void setProwadzacy(std::string prowadzacy);
	void setIloscGodzinPracyWlasnej(int iloscGodzinPracyWlasnej);
    std::string getNazwa();
    std::string getOpis();
	float getPunktyEtcs();
    std::string getProwadzacy();
	int getIloscGodzinPracyWlasnej();
	Przedmiot(std::string nazwa, std::string opis, float punktyEtcs, std::string prowadzacy, int iloscGodzinPracyWlasnej);
	~Przedmiot();
	void wyswietlOpis();
	void wyswietlProwadzacego();
	void wyswietlIloscGodzinPracyWlasnej();
private:
    std::string nazwa;
    std::string opis;
	float punktyEtcs;
    std::string prowadzacy;
	int iloscGodzinPracyWlasnej;
};

#endif  //_PRZEDMIOT_H
