//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03b
//  @ File Name : Przedmiot.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include "Przedmiot.h"

void Przedmiot::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Przedmiot::setOpis(std::string opis) {
    this->opis = opis;
}

void Przedmiot::setPunktyEtcs(float punktyEtcs) {
    this->punktyEtcs = punktyEtcs;
}

void Przedmiot::setProwadzacy(std::string prowadzacy) {
    this->prowadzacy = prowadzacy;
}

void Przedmiot::setIloscGodzinPracyWlasnej(int iloscGodzinPracyWlasnej) {
    this->iloscGodzinPracyWlasnej = iloscGodzinPracyWlasnej;
}

std::string Przedmiot::getNazwa() {
    return nazwa;
}

std::string Przedmiot::getOpis() {
    return opis;
}

float Przedmiot::getPunktyEtcs() {
    return punktyEtcs;
}

std::string Przedmiot::getProwadzacy() {
    return prowadzacy;
}

int Przedmiot::getIloscGodzinPracyWlasnej() {
    return iloscGodzinPracyWlasnej;
}

Przedmiot::Przedmiot(std::string nazwa, std::string opis, float punktyEtcs, std::string prowadzacy, int iloscGodzinPracyWlasnej) {
    this->nazwa = nazwa;
    this->opis = opis;
    this->punktyEtcs = punktyEtcs;
    this->prowadzacy = prowadzacy;
    this->iloscGodzinPracyWlasnej = iloscGodzinPracyWlasnej;
}

Przedmiot::~Przedmiot() {}

void Przedmiot::wyswietlOpis() {
    std::cout << "Opis " << getNazwa() << ": " << getOpis() << "\n";
}

void Przedmiot::wyswietlProwadzacego() {
    std::cout << "Prowadzacy z przedmiotu " << getNazwa() << ": " << getProwadzacy() << "\n";
}

void Przedmiot::wyswietlIloscGodzinPracyWlasnej() {
    std::cout << "Ilosc godzin pracy wlasnej z przedmiotu " << getNazwa() << ": " << getIloscGodzinPracyWlasnej() << "\n";
}
