//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03b
//  @ File Name : Student.h
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_STUDENT_H)
#define _STUDENT_H

#include <string>

using namespace std;

class Student {
public:
	string getFirstName();
	void setFirstName(string firstName);
	string getLastName();
	void setLastName(string lastName);
	int getAge();
	void setAge(int age);
	float getAverage();
	void setAverage(float average);
	int getYearOfUniversity();
	void setYearOfUniversity(int yearOfUniversity);
	Student(string firstName, string lastName, int age, float average, int yearOfUniversity);
	~Student();
	void doHomework();
	void attendLecture();
	void attendLaboratory();
private:
	string firstName;
	string lastName;
	int age;
	float average;
	int yearOfUniversity;
};

#endif  //_STUDENT_H
