//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03b
//  @ File Name : Student.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include <string>

class Student {
public:
	void setImie(std::string imie);
	void setNazwisko(std::string nazwisko);
	void setWiek(int wiek);
	void setSrednia(float srednia);
	void setRokStudiow(int rokStudiow);
    std::string getImie();
    std::string getNazwisko();
	int getWiek();
	float getSrednia();
	int getRokStudiow();
	Student(std::string imie, std::string nazwisko, int wiek, float srednia, int rokStudiow);
	~Student();
	void zrobPraceDomowa();
	void zglosSieNaWykladzie();
	void zglosSieNaCwiczeniach();
private:
    std::string imie;
    std::string nazwisko;
	int wiek;
	float srednia;
	int rokStudiow;
};

#endif  //_STUDENT_H
