//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 29.03.2023
//  @ Author : 
//
//


#include "Student.h"

void Student::setImie(string imie) {

}

void Student::setNazwisko(string nazwisko) {

}

void Student::setWiek(int wiek) {

}

void Student::setSrednia(float srednia) {

}

void Student::setRokStudiow(int rokStudiow) {

}

string Student::getImie() {

}

string Student::getNazwisko() {

}

int Student::getWiek() {

}

float Student::getSrednia() {

}

int Student::getRokStudiow() {

}

void Student::Student(string imie, string nazwisko, int wiek, float srednia, int rokStudiow) {

}

void Student::Student() {

}

void Student::zrobPraceDomowa() {

}

void Student::zglosSieNaWykladzie() {

}

void Student::zglosSieNaCwiczeniach() {

}

