//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 29.03.2023
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H


class Student {
public:
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	void setWiek(int wiek);
	void setSrednia(float srednia);
	void setRokStudiow(int rokStudiow);
	string getImie();
	string getNazwisko();
	int getWiek();
	float getSrednia();
	int getRokStudiow();
	void Student(string imie, string nazwisko, int wiek, float srednia, int rokStudiow);
	void Student();
	void zrobPraceDomowa();
	void zglosSieNaWykladzie();
	void zglosSieNaCwiczeniach();
private:
	string imie;
	string nazwisko;
	int wiek;
	float srednia;
	int rokStudiow;
};

#endif  //_STUDENT_H
