//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03b
//  @ File Name : UniversitySubject.h
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_UNIVERSITYSUBJECT_H)
#define _UNIVERSITYSUBJECT_H

#include <string>

using namespace std;

class UniversitySubject {
public:
	string getName();
	void setName(string name);
	string getDescription();
	void setDescription(string description);
	float getETCSPoints();
	void setETCSPoints(float ETCSPoints);
	string getLecturer();
	void setLecturer(string lecturer);
	int getNumberOfUnassistedWorkHours();
	void setNumberOfUnassistedWorkHours(int numberOfUnassistedWorkHours);
	UniversitySubject(string name, string description, float ETCSPoints, string lecturer, int numberOfUnassistedWorkHours);
	~UniversitySubject();
	void printDescription();
	void printLecturer();
	void printNumberOfUnassistedWorkHours();
private:
	string name;
	string description;
	float ETCSPoints;
	string lecturer;
	int numberOfUnassistedWorkHours;
};

#endif  //_UNIVERSITYSUBJECT_H
