//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : BernouliDiagram.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BERNOULIDIAGRAM_H)
#define _BERNOULIDIAGRAM_H

#include "BinomialTheorem.h"
#include "Power.h"

/**
 * Class representing a Bernouli diagram
 */
class BernouliDiagram {
public:

	/**
	 * Gets the probability of success
	 *
	 * @param p The probability of success
	 * @param n The number of trials
	 * @param k The number of successes
	 *
	 * @return The probability of success
	 */
    long double bernouliDiagram(double p, int n, int k);

	/**
	 * Constructor
	 */
    BernouliDiagram();

	/**
	 * Destructor
	 */
    ~BernouliDiagram();

private:

	/**
	 * The probability of success
	 */
	double q;

	/**
	 * The number of trials
	 */
	long double p;

	/**
	 * The number of successes
	 */
	Power * powerPtr;

	/**
	 * The binomial theorem
	 */
	BinomialTheorem * binomialTheoremPtr;
};

#endif  //_BERNOULIDIAGRAM_H
