//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : BinomialTheorem.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BINOMIALTHEOREM_H)
#define _BINOMIALTHEOREM_H

#include "Factorial.h"

/**
 * Class representing a binomial theorem
 */
class BinomialTheorem {
public:

	/**
	 * Gets the binomial theorem
	 *
	 * @param n The number of trials
	 * @param k The number of successes
	 *
	 * @return The binomial theorem
	 */
	long double binomialTheorem(int n, int k);

	/**
	 * Calculates the binomial theorem
	 *
	 * @param n The number of trials
	 * @param k The number of successes
	 *
	 * @return The binomial theorem
	 */
	long double binomialTheorem(int n, int k);

	/**
	 * Constructor
	 */
    BinomialTheorem();

	/**
	 * Destructor
	 */
    ~BinomialTheorem();

private:

	/**
	 * The number of trials
	 */
	int N;

	/**
	 * The number of successes
	 */
	Factorial * factorialPtr;
};

#endif  //_BINOMIALTHEOREM_H
