//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : Power.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_POWER_H)
#define _POWER_H

/**
 * Class representing a power
 */
class Power {
public:

	/**
	 * Calculates the power
	 *
	 * @param base The base
	 * @param exponent The exponent
	 *
	 * @return The power
	 */
	double power(double base, int exponent);
};

#endif  //_POWER_H
