//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 06
//  @ File Name : User.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>

#include "User.h"

string User::getId() {
    return id;
}

void User::setId(string id) {
    this->id = id;
}

string User::getPassword() {
    return password;
}

void User::setPassword(string password) {
    this->password = password;
}

string User::getName() {
    return name;
}

void User::setName(string name) {
    this->name = name;
}

string User::getSurname() {
    return surname;
}

void User::setSurname(string surname) {
    this->surname = surname;
}

string User::getEmail() {
    return email;
}

void User::setEmail(string email) {
    this->email = email;
}

User::User(string id, string password, string name, string surname, string email) {
    setId(id);
    setPassword(password);
    setName(name);
    setSurname(surname);
    setEmail(email);
}

User::~User() {}

pair<string, string> User::logIn() {
    cout << "---------------------------------------------------------------------------------------\n";
    cout << "----------------------------------------Log in-----------------------------------------\n";
    cout << "---------------------------------------------------------------------------------------\n";
    string id;
    string password;

    cout << "ID: ";
    cin >> id;

    cout << "Password: ";
    cin >> password;

    return make_pair(id, password);
}

void User::registerUser() {
    cout << "---------------------------------------------------------------------------------------\n";
    cout << "---------------------------------------Register----------------------------------------\n";
    cout << "---------------------------------------------------------------------------------------\n";
    string userInput;

    cout << "ID: ";
    cin >> userInput;
    setId(userInput);

    cout << "Password: ";
    cin >> userInput;
    setPassword(userInput);

    cout << "Name: ";
    cin >> userInput;
    setName(userInput);

    cout << "Surname: ";
    cin >> userInput;
    setSurname(userInput);

    cout << "Email: ";
    cin >> userInput;
    setEmail(userInput);
}

void User::openHomePage() {
    cout << "---------------------------------------------------------------------------------------\n";
    cout << "---------------------------------------Home Page---------------------------------------\n";
    cout << "---------------------------------------------------------------------------------------\n";
}
