//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 06
//  @ File Name : User.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_USER_H)
#define _USER_H

#include <string>

using namespace std;

/**
 * Class representing a user
 */
class User {
public:

	/**
	 * Gets the id of the user
	 *
	 * @return The id of the user
	 */
	string getId();

	/**
	 * Sets the id of the user
	 *
	 * @param id The id of the user
	 */
	void setId(string id);

	/**
	 * Gets the password of the user
	 *
	 * @return The password of the user
	 */
	string getPassword();

	/**
	 * Sets the password of the user
	 *
	 * @param password The password of the user
	 */
	void setPassword(string password);

	/**
	 * Gets the name of the user
	 *
	 * @return The name of the user
	 */
	string getName();

	/**
	 * Sets the name of the user
	 *
	 * @param name The name of the user
	 */
	void setName(string name);

	/**
	 * Gets the surname of the user
	 *
	 * @return The surname of the user
	 */
	string getSurname();

	/**
	 * Sets the surname of the user
	 *
	 * @param surname The surname of the user
	 */
	void setSurname(string surname);

	/**
	 * Gets the email of the user
	 *
	 * @return The email of the user
	 */
	string getEmail();

	/**
	 * Sets the email of the user
	 *
	 * @param email The email of the user
	 */
	void setEmail(string email);

	/**
	 * Constructor
	 *
	 * @param id The id of the user
	 * @param password The password of the user
	 * @param name The name of the user
	 * @param surname The surname of the user
	 * @param email The email of the user
	 */
	User(string id, string password, string name, string surname, string email);

	/**
	 * Destructor
	 */
	~User();

	/**
	 * Logs in the user
	 *
	 * @return The id and password of the user
	 */
    static pair<string, string> logIn();

	/**
	 * Registers the user
	 */
    void registerUser();

	/**
	 * Opens the home page
	 */
	static void openHomePage();

private:

	/**
	 * The id of the user
	 */
	string id;

	/**
	 * The password of the user
	 */
	string password;

	/**
	 * The name of the user
	 */
	string name;

	/**
	 * The surname of the user
	 */
	string surname;

	/**
	 * The email of the user
	 */
	string email;
};

#endif  //_USER_H
