//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : A.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_A_H)
#define _A_H

#include "B.h"

class A {
public:
	void fooA();
private:
	B * b;
	int n = 0;
};

#endif  //_A_H
