//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : B.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_B_H)
#define _B_H

//#include "C.h"

class B {
public:
	void fooB();
private:
//	C * c;
};

#endif  //_B_H
