//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : C.cpp
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "C.h"

void C::fooC() {
    if(x > 0) {
        b->fooB();
    }
}
