//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03d
//  @ File Name : Produkt.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_PRODUKT_H)
#define _PRODUKT_H

#include <string>

class Produkt {
public:
	void setNazwa(std::string nazwa);
	void setIlosc(int ilosc);
	void setSklad(std::string sklad);
	void setWaga(float waga);
	void setDataWaznosci(std::string dataWaznosci);
    std::string getNazwa();
	int getIlosc();
    std::string getSklad();
	float getWaga();
    std::string getDataWaznosci();
	Produkt(std::string nazwa, int ilosc, std::string sklad, float waga, std::string dataWaznosci);
	~Produkt();
private:
    std::string nazwa;
	int ilosc;
    std::string sklad;
	float waga;
    std::string dataWaznosci;
};

#endif  //_PRODUKT_H
