//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03d
//  @ File Name : Product.h
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_PRODUCT_H)
#define _PRODUCT_H

#include <string>

using namespace std;

class Product {
public:
	string getName();
	void setName(string name);
	int getQuantity();
	void setQuantity(int quantity);
	string getComposition();
	void setComposition(string composition);
	float getWeight();
	void setWeight(float weight);
	string getExpirationDate();
	void setExpirationDate(string expirationDate);
	Product(string name, int quantity, string composition, float weight, string expirationDate);
	~Product();
	void sellProduct();
	void putProductOnShelves();
	void restockProduct();
private:
	string name;
	int quantity;
	string composition;
	float weight;
	string expirationDate;
};

#endif  //_PRODUCT_H
