//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03d
//  @ File Name : Sklep.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SKLEP_H)
#define _SKLEP_H

#include "Produkt.h"

class Sklep {
public:
	void setNazwa(std::string nazwa);
	void setRodzaj(std::string rodzaj);
	void setWielkosc(std::string wielkosc);
	void setGodzinyOtwarcia(std::string godzinyOtwarcia);
	void setProdukt(std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu);
    std::string getNazwa();
    std::string getRodzaj();
    std::string getWielkosc();
    std::string getGodzinyOtwarcia();
	void printProdukt();
	Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc, std::string godzinyOtwarcia,
          Produkt produktSklepu);
	~Sklep();
private:
    std::string nazwa;
    std::string rodzaj;
    std::string wielkosc;
    std::string godzinyOtwarcia;
    Produkt produktSklepu;
};

#endif  //_SKLEP_H
