//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : B.cpp
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>

#include "B.h"

using namespace std;

void B::fooB() {
    cout << "fooB" << endl;
}
