//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : C.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_C_H)
#define _C_H

#include "B.h"

class C {
public:

	void fooC();

private:

	B * b;
	int x;
};

#endif  //_C_H
