//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : BernouliDiagram.cpp
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include "BernouliDiagram.h"

using namespace std;

BernouliDiagram::BernouliDiagram() {
    binomialTheoremPtr = new BinomialTheorem();
    powerPtr = new Power();
}

BernouliDiagram::~BernouliDiagram() {
    delete binomialTheoremPtr;
    delete powerPtr;
}

long double BernouliDiagram::bernouliDiagramRecursively(double p, int n, int k) {
    q = 1 - p;
    return ((binomialTheoremPtr->binomialTheoremRecursively(n, k)) * (powerPtr->powerRecursively(p, k)) * powerPtr->powerRecursively(q, n - k));
}

long double BernouliDiagram::bernouliDiagramIteratively(double p, int n, int k) {
    q = 1 - p;
    return ((binomialTheoremPtr->binomialTheoremIteratively(n, k)) * (powerPtr->powerIteratively(p, k)) * powerPtr->powerIteratively(q, n - k));
}
