//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : BinomialTheorem.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BINOMIALTHEOREM_H)
#define _BINOMIALTHEOREM_H

#include "Factorial.h"

class BinomialTheorem {
public:
	BinomialTheorem();
	~BinomialTheorem();
	long double binomialTheoremRecursively(int n, int k);
	long double binomialTheoremIteratively(int n, int k);
private:
	int N;
	Factorial * factorialPtr;
};

#endif  //_BINOMIALTHEOREM_H
