//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : Factorial.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H

class Factorial {
public:
	long double factorialRecursively(int n);
	long double factorialIteratively(int n);
};

#endif  //_FACTORIAL_H
