//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : System.h
//  @ Date : 19.04.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <string>
#include <vector>
#include "User.h"

class System {
public:
	void setNazwa(std::string nazwa);
	void setTechnologia(std::string technologia);
	void setCzyDzialaSzybko(bool czyDzialaSzybko);
	void setCzyJestResponsywny(bool czyJestResponsywny);
    std::string getNazwa();
    std::string getTechnologia();
	bool getCzyDzialaSzybko();
	bool getCzyJestResponsywny();
	void dodajUzytkownika(User * uzytkownik);
	void usunUzytkownika(User * uzytkownik);
	static void wyswietlUzytkownika(User * uzytkownik);
    bool uwierzytelnianie(std::string identyfikator, std::string haslo);
    System(std::string nazwa, std::string technologia, bool czyDzialaSzybko, bool czyJestResponsywny);
private:
    std::string nazwa;
    std::string technologia;
	bool czyDzialaSzybko;
	bool czyJestResponsywny;
	std::vector<User *> uzytkownicy;
};

#endif  //_SYSTEM_H
