//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 06
//  @ File Name : System.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <string>
#include <vector>
#include "User.h"

class System {
public:
	string getName();
	void setName(string name);
	string getTechnology();
	void setTechnology(string technology);
	string getPerformance();
	void setPerformance(string performance);
	string getFunctionality();
	void setFunctionality(string functionality);
	string getSecurity();
	void setSecurity(string security);
	System(string name, string technology, string performance, string functionality, string security);
	~System();
	bool authentication(string userName, string userPassword);
	void addUser(User user);
	void printUser(User * user);
	void deleteUser(User user);
    void boot();
private:
	string name;
	string technology;
	string performance;
	string functionality;
	string security;
	vector <User *> users;
};

#endif  //_SYSTEM_H
