//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : System.cpp
//  @ Date : 19.04.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "System.h"

void System::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void System::setTechnologia(std::string technologia) {
    this->technologia = technologia;
}

void System::setCzyDzialaSzybko(bool czyDzialaSzybko) {
    this->czyDzialaSzybko = czyDzialaSzybko;
}

void System::setCzyJestResponsywny(bool czyJestResponsywny) {
    this->czyJestResponsywny = czyJestResponsywny;
}

std::string System::getNazwa() {
    return nazwa;
}

std::string System::getTechnologia() {
    return technologia;
}

bool System::getCzyDzialaSzybko() {
    return czyDzialaSzybko;
}

bool System::getCzyJestResponsywny() {
    return czyJestResponsywny;
}

System::System(std::string nazwa, std::string technologia, bool czyDzialaSzybko, bool czyJestResponsywny) {
    this->nazwa = nazwa;
    this->technologia = technologia;
    this->czyDzialaSzybko = czyDzialaSzybko;
    this->czyJestResponsywny = czyJestResponsywny;
}

void System::dodajUzytkownika(User * uzytkownik) {
    User * nowyUzytkownik = new User(uzytkownik->getIdentyfikator(), uzytkownik->getHaslo(), uzytkownik->getImie(), uzytkownik->getNazwisko(), uzytkownik->getEmail());
    uzytkownicy.push_back(nowyUzytkownik);
}

void System::usunUzytkownika(User * uzytkownik) {
    for(std::vector<User *>::iterator it = uzytkownicy.begin(); it != uzytkownicy.end(); it++) {
        if(*it == uzytkownik) {
            uzytkownicy.erase(it);
        }
    }
}

void System::wyswietlUzytkownika(User * uzytkownik) {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "--------------------------------------Uzytkownik---------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "Identyfikator: " << uzytkownik->getIdentyfikator() << ", Imie: " << uzytkownik->getImie() << ", Nazwisko: " << uzytkownik->getNazwisko() << "\n";
    std::cout << "Email: " << uzytkownik->getEmail() << "\n";
}

bool System::uwierzytelnianie(std::string identyfikator, std::string haslo) {
    for(auto & i : uzytkownicy) {
        if((i->getIdentyfikator() == identyfikator) && (i->getHaslo() == haslo)) {
            return true;
        }
    }
    return false;
}
