//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : System.cpp
//  @ Date : 13.04.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "System.h"
#include "User.h"

void System::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void System::setTechnologia(std::string technologia) {
    this->technologia = technologia;
}

void System::setCzyDzialaSzybko(bool czyDzialaSzybko) {
    this->czyDzialaSzybko = czyDzialaSzybko;
}

void System::setCzyJestResponsywny(bool czyJestResponsywny) {
    this->czyJestResponsywny = czyJestResponsywny;
}

std::string System::getNazwa() {
    return nazwa;
}

std::string System::getTechnologia() {
    return technologia;
}

bool System::getCzyDzialaSzybko() {
    return czyDzialaSzybko;
}

bool System::getCzyJestResponsywny() {
    return czyJestResponsywny;
}

void System::dodajUzytkownika(User * uzytkownik) {
    uzytkownicy.push_back(uzytkownik);
}

void System::usunUzytkownika(User * uzytkownik) {
    for(std::vector<User *>::iterator it = uzytkownicy.begin(); it != uzytkownicy.end(); it++) {
        if(*it == uzytkownik) {
            uzytkownicy.erase(it);
        }
    }
}

void System::wyswietlUzytkownika(User * uzytkownik) {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "--------------------------------------Uzytkownik---------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "Identyfikator: " << uzytkownik->getIdentyfikator() << ", Imie: " << uzytkownik->getImie() << ", Nazwisko: " << uzytkownik->getNazwisko() << "\n";
    std::cout << "Email: " << uzytkownik->getEmail();
}

bool System::uwierzytelnianie(std::string identyfikator, std::string haslo) {
    for(int i = 0; i < uzytkownicy.size(); i++) {
        if((uzytkownicy[i]->getIdentyfikator() == identyfikator) && (uzytkownicy[i]->getHaslo() == haslo)) {
            return true;
        }
    }
    return false;
}

System::System(std::string nazwa, std::string technologia, bool czyDzialaSzybko, bool czyJestResponsywny) {
    this->nazwa = nazwa;
    this->technologia = technologia;
    this->czyDzialaSzybko = czyDzialaSzybko;
    this->czyJestResponsywny = czyJestResponsywny;
}
