//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 06
//  @ File Name : User.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_USER_H)
#define _USER_H

#include <string>

using namespace std;

class User {
public:
	string getId();
	void setId(string id);
	string getPassword();
	void setPassword(string password);
	string getName();
	void setName(string name);
	string getSurname();
	void setSurname(string surname);
	string getEmail();
	void setEmail(string email);
	User(string id, string password, string name, string surname, string email);
	~User();
    static pair<string, string> logIn();
    void registerUser();
	static void openHomePage();
private:
	string id;
	string password;
	string name;
	string surname;
	string email;
};

#endif  //_USER_H
