//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : User.h
//  @ Date : 19.04.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_USER_H)
#define _USER_H

#include <string>

class User {
public:
	void setIdentyfikator(std::string identyfikator);
	void setHaslo(std::string haslo);
	void setImie(std::string imie);
	void setNazwisko(std::string nazwisko);
	void setEmail(std::string email);
    std::string getIdentyfikator();
    std::string getHaslo();
    std::string getImie();
    std::string getNazwisko();
    std::string getEmail();
	void zalogujSie();
    void zarejestrujSie();
	static void zalogowano();
    static void otworzKatalogStronyDomowej();
    User * wyslijDane();
    User(std::string identyfikator, std::string haslo, std::string imie, std::string nazwisko, std::string email);
private:
    std::string identyfikator;
    std::string haslo;
    std::string imie;
    std::string nazwisko;
    std::string email;
};

#endif  //_USER_H
