//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : User.cpp
//  @ Date : 19.04.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "User.h"

void User::setIdentyfikator(std::string identyfikator) {
    this->identyfikator = identyfikator;
}

void User::setHaslo(std::string haslo) {
    this->haslo = haslo;
}

void User::setImie(std::string imie) {
    this->imie = imie;
}

void User::setNazwisko(std::string nazwisko) {
    this->nazwisko = nazwisko;
}

void User::setEmail(std::string email) {
    this->email = email;
}

std::string User::getIdentyfikator() {
    return identyfikator;
}

std::string User::getHaslo() {
    return haslo;
}

std::string User::getImie() {
    return imie;
}

std::string User::getNazwisko() {
    return nazwisko;
}

std::string User::getEmail() {
    return email;
}

void User::zalogujSie() {
    std::string input;

    std::cout << "Podaj identyfikator: ";
    std::cin >> input;
    setIdentyfikator(input);

    std::cout << "Podaj haslo: ";
    std::cin >> input;
    setHaslo(input);
}

void User::otworzKatalogStronyDomowej() {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "-----------------------------------------Sklep-----------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
}

void User::zalogowano() {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "--------------------------------------Zalogowano---------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
}

void User::zarejestrujSie() {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "--------------------------------------Rejestracja--------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::string input;

    std::cout << "Podaj identyfikator: ";
    std::cin >> input;
    setIdentyfikator(input);

    std::cout << "Podaj haslo: ";
    std::cin >> input;
    setHaslo(input);

    std::cout << "Podaj imie: ";
    std::cin >> input;
    setImie(input);

    std::cout << "Podaj nazwisko: ";
    std::cin >> input;
    setNazwisko(input);

    std::cout << "Podaj email: ";
    std::cin >> input;
    setEmail(input);

    wyslijDane();
}

User * User::wyslijDane() {
    return this;
}

User::User(std::string identyfikator, std::string haslo, std::string imie, std::string nazwisko, std::string email) {
    this->identyfikator = identyfikator;
    this->haslo = haslo;
    this->imie = imie;
    this->nazwisko = nazwisko;
    this->email = email;
}
