//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 06
//  @ File Name : User.cpp
//  @ Date : 13.04.2023
//  @ Author : Tomasz Wnuk
//
//

#include "User.h"
#include <iostream>

void User::setIdentyfikator(std::string identyfikator) {
    this->identyfikator = identyfikator;
}

void User::setHaslo(std::string haslo) {
    this->haslo = haslo;
}

void User::setImie(std::string imie) {
    this->imie = imie;
}

void User::setNazwisko(std::string nazwisko) {
    this->nazwisko = nazwisko;
}

void User::setEmail(std::string email) {
    this->email = email;
}

std::string User::getIdentyfikator() {
    return identyfikator;
}

std::string User::getHaslo() {
    return haslo;
}

std::string User::getImie() {
    return imie;
}

std::string User::getNazwisko() {
    return nazwisko;
}

std::string User::getEmail() {
    return email;
}

void User::otworzKatalogStronyDomowej(System * system) {
    std::cout << "---------------------------------------------------------------------------------------\n";
    std::cout << "-----------------------------------------Sklep-----------------------------------------\n";
    std::cout << "---------------------------------------------------------------------------------------\n";
    zalogujSie(system);
}

void User::zalogujSie(System * system) {
    std::cout << "Podaj identyfikator: ";
    std::cin >> identyfikator;

    std::cout << "Podaj haslo: ";
    std::cin >> haslo;

    logowanie(system, identyfikator, haslo);
}

void User::logowanie(System * system, std::string identyfikator, std::string haslo) {
    if(system->uwierzytelnianie(identyfikator, haslo)) {
        std::cout << "---------------------------------------------------------------------------------------\n";
        std::cout << "--------------------------------------Zalogowano---------------------------------------\n";
        std::cout << "---------------------------------------------------------------------------------------\n";
        return;
    } else {
        zarejestrujSie(system);
    }
}

void User::zarejestrujSie(System * system) {
    User * uzytkownik = new User(identyfikator, haslo, imie, nazwisko, email);
    wyslijDane(system, uzytkownik);
}

void User::wyslijDane(System * system, User * uzytkownik) {
    system->dodajUzytkownika(uzytkownik);
}

User::User(std::string identyfikator, std::string haslo, std::string imie, std::string nazwisko, std::string email) {
    this->identyfikator = std::move(identyfikator);
    this->haslo = std::move(haslo);
    this->imie = std::move(imie);
    this->nazwisko = std::move(nazwisko);
    this->email = std::move(email);
}

User::User() {

}
