//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 04c
//  @ File Name : Product.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>

#include "Product.h"

using namespace std;

string Product::getName() {
    return name;
}

void Product::setName(string name) {
    this->name = name;
}

int Product::getQuantity() {
    return quantity;
}

void Product::setQuantity(int quantity) {
    this->quantity = quantity;
}

string Product::getComposition() {
    return composition;
}

void Product::setComposition(string composition) {
    this->composition = composition;
}

float Product::getWeight() {
    return weight;
}

void Product::setWeight(float weight) {
    this->weight = weight;
}

string Product::getExpirationDate() {
    return expirationDate;
}

void Product::setExpirationDate(string expirationDate) {
    this->expirationDate = expirationDate;
}

Product::Product(string name, int quantity, string composition, float weight, string expirationDate) {
    setName(name);
    setQuantity(quantity);
    setComposition(composition);
    setWeight(weight);
    setExpirationDate(expirationDate);
}

Product::~Product() {}

void Product::sellProduct() {
    cout << "Product has been sold" << endl;
    quantity--;
}

void Product::putProductOnShelves() {
    cout << "Product " << name << " has been put on shelves" << endl;
}

void Product::restockProduct() {
    cout << "Product has been restocked" << endl;
    quantity += 100;
}
