//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Czlowiek.h
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_CZLOWIEK_H)
#define _CZLOWIEK_H


#include <string>
#include "Sklep.h"
#include "Golab.h"
#include "Kot.h"

class Czlowiek {
public:
	void setImie(std::string imie);
	void setHobby(std::string hobby);
	void setWiek(int wiek);
	void setMaCzas(bool maCzas);
	void setKarmionyGolab(Golab * karmionyGolab);
    std::string getImie();
    std::string getHobby();
	int getWiek();
	bool getMaCzas();
	Czlowiek(std::string imie, std::string hobby, int wiek, bool maCzas);
    ~Czlowiek();
private:
    std::string imie;
    std::string hobby;
	int wiek;
	bool maCzas;
    Golab * karmionyGolab;
};

#endif  //_CZLOWIEK_H
