//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Czlowiek.cpp
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Czlowiek.h"

void Czlowiek::setImie(std::string imie) {
    this->imie = imie;
}

void Czlowiek::setHobby(std::string hobby) {
    this->hobby = hobby;
}

void Czlowiek::setWiek(int wiek) {
    this->wiek = wiek;
}

void Czlowiek::setMaCzas(bool maCzas) {
    this->maCzas = maCzas;
}

void Czlowiek::setKarmionyGolab(Golab * karmionyGolab) {
    this->karmionyGolab = karmionyGolab;
}

std::string Czlowiek::getImie() {
    return imie;
}

std::string Czlowiek::getHobby() {
    return hobby;
}

int Czlowiek::getWiek() {
    return wiek;
}

bool Czlowiek::getMaCzas() {
    return maCzas;
}

Czlowiek::Czlowiek(std::string imie, std::string hobby, int wiek, bool maCzas) {
    this->imie = imie;
    this->hobby = hobby;
    this->wiek = wiek;
    this->maCzas = maCzas;
}

Czlowiek::~Czlowiek() {};
