//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Golab.h
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_GOLAB_H)
#define _GOLAB_H


#include "Czlowiek.h"

class Golab {
public:
	void setKarmiacyCzlowiek(Czlowiek * newCzlowiek);
	void setUmaszczenie(std::string umaszczenie);
	void setDlugoscCiala(int dlugoscCiala);
	void setKrepy(bool krepy);
	void setWiek(int wiek);
    Czlowiek getKarmiacyCzlowiek();
    std::string getUmaszczenie();
	int getDlugoscCiala();
	bool getKrepy();
	int getWiek();
	Golab(std::string umaszczenie, int dlugoscCiala, bool krepy, int wiek);
	~Golab();
private:
    Czlowiek * karmiacyCzlowiek;
    std::string umaszczenie;
	int dlugoscCiala;
	bool krepy;
	int wiek;
};

#endif  //_GOLAB_H
