//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Golab.cpp
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Golab.h"

void Golab::setKarmiacyCzlowiek(Czlowiek * newCzlowiek) {
    this->karmiacyCzlowiek = newCzlowiek;
}

void Golab::setUmaszczenie(std::string umaszczenie) {
    this->umaszczenie = umaszczenie;
}

void Golab::setDlugoscCiala(int dlugoscCiala) {
    this->dlugoscCiala = dlugoscCiala;
}

void Golab::setKrepy(bool krepy) {
    this->krepy = krepy;
}

void Golab::setWiek(int wiek) {
    this->wiek = wiek;
}

Czlowiek Golab::getKarmiacyCzlowiek() {
    return * karmiacyCzlowiek;
}

std::string Golab::getUmaszczenie() {
    return umaszczenie;
}

int Golab::getDlugoscCiala() {
    return dlugoscCiala;
}

bool Golab::getKrepy() {
    return krepy;
}

int Golab::getWiek() {
    return wiek;
}

Golab::Golab(std::string umaszczenie, int dlugoscCiala, bool krepy, int wiek) {
    this->umaszczenie = umaszczenie;
    this->dlugoscCiala = dlugoscCiala;
    this->krepy = krepy;
    this->wiek = wiek;
}

Golab::~Golab() {}
