//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Kot.cpp
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Kot.h"
#include "Czlowiek.h"

void Kot::setImie(std::string imie) {
    this->imie = imie;
}

void Kot::setKolor(std::string kolor) {
    this->kolor = kolor;
}

void Kot::setWiek(int wiek) {
    this->wiek = wiek;
}

void Kot::setPoglaskany(Czlowiek * ptrCzlowiek, bool poglaskany) {
    if((poglaskany) && (ptrCzlowiek->getMaCzas())) {
        this->poglaskany = true;
    } else {
        this->poglaskany = false;
    }
}

void Kot::setNajedzony(Czlowiek * ptrCzlowiek, bool najedzony) {
    if((najedzony) && (ptrCzlowiek->getMaCzas())) {
        this->najedzony = true;
    } else {
        this->najedzony = false;
    }
}

std::string Kot::getImie() {
    return imie;
}

std::string Kot::getKolor() {
    return kolor;
}

int Kot::getWiek() {
    return wiek;
}

bool Kot::getPoglaskany() {
    return poglaskany;
}

bool Kot::getNajedzony() {
    return najedzony;
}

Kot::Kot(std::string imie, std::string kolor, int wiek, bool poglaskany, bool najedzony) {
    this->imie = imie;
    this->kolor = kolor;
    this->wiek = wiek;
    this->poglaskany = poglaskany;
    this->najedzony = najedzony;
}

Kot::~Kot() {}
