//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Kot.h
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_KOT_H)
#define _KOT_H

#include "Czlowiek.h"

class Kot {
public:
	void setImie(std::string imie);
	void setKolor(std::string kolor);
	void setWiek(int wiek);
	void setPoglaskany(Czlowiek * ptrCzlowiek, bool poglaskany);
	void setNajedzony(Czlowiek * ptrCzlowiek, bool najedzony);
    std::string getImie();
    std::string getKolor();
	int getWiek();
	bool getPoglaskany();
	bool getNajedzony();
	Kot(std::string imie, std::string kolor, int wiek, bool poglaskany, bool najedzony);
	~Kot();
private:
    std::string imie;
    std::string kolor;
	int wiek;
	bool poglaskany;
	bool najedzony;
};

#endif  //_KOT_H
