//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03a
//  @ File Name : Opiekun.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "Opiekun.h"

void Opiekun::setImie(std::string imie) {
    this->imie = imie;
}

void Opiekun::setWzrost(float wzrost) {
    this->wzrost = wzrost;
}

void Opiekun::setWiek(int wiek) {
    this->wiek = wiek;
}

void Opiekun::setHobby(std::string hobby) {
    this->hobby = hobby;
}

void Opiekun::setMozeZajacSieKotem(bool mozeZajacSieKotem) {
    this->mozeZajacSieKotem = mozeZajacSieKotem;
}

std::string Opiekun::getImie() {
    return imie;
}

float Opiekun::getWzrost() {
    return wzrost;
}

int Opiekun::getWiek() {
    return wiek;
}

std::string Opiekun::getHobby() {
    return hobby;
}

bool Opiekun::getMozeZajacSieKotem() {
    return mozeZajacSieKotem;
}

Opiekun::Opiekun(std::string imie, float wzrost, int wiek, std::string hobby, bool mozeZajacSieKotem) {
    this->imie = imie;
    this->wzrost = wzrost;
    this->wiek = wiek;
    this->hobby = hobby;
    this->mozeZajacSieKotem = mozeZajacSieKotem;
}

Opiekun::~Opiekun() {}

void Opiekun::zajmijSieSwoimHobby() {
    std::cout << getImie() << " zajmuje sie swoim hobby. \n";
}

void Opiekun::zrobZakupy() {
    std::cout << getImie() << " robi zakupy. \n";
}
