//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Produkt.cpp
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Produkt.h"


void Produkt::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Produkt::setIlosc(int ilosc) {
    this->ilosc = ilosc;
}

void Produkt::setSklad(std::string sklad) {
    this->sklad = sklad;
}

void Produkt::setWaga(float waga) {
    this->waga = waga;
}

void Produkt::setDataWaznosci(std::string dataWaznosci) {
    this->dataWaznosci = dataWaznosci;
}

std::string Produkt::getNazwa() {
    return nazwa;
}

int Produkt::getIlosc() {
    return ilosc;
}

std::string Produkt::getSklad() {
    return sklad;
}

float Produkt::getWaga() {
    return waga;
}

std::string Produkt::getDataWaznosci() {
    return dataWaznosci;
}

Produkt::Produkt(std::string nazwa, int ilosc, std::string sklad, float waga, std::string dataWaznosci) {
    this->nazwa = nazwa;
    this->ilosc = ilosc;
    this->sklad = sklad;
    this->waga = waga;
    this->dataWaznosci = dataWaznosci;
}

Produkt::~Produkt() {}
