//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Sklep.cpp
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "Sklep.h"
#include "Czlowiek.h"

void Sklep::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Sklep::setRodzaj(std::string rodzaj) {
    this->rodzaj = rodzaj;
}

void Sklep::setWielkosc(std::string wielkosc) {
    this->wielkosc = wielkosc;
}

void Sklep::setKupujacy(Czlowiek kupujacy) {
    this->kupujacy = kupujacy;
}

void Sklep::setProdukt(std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu) {
    produktSklepu.setNazwa(nazwa);
    produktSklepu.setIlosc(iloscProduktu);
    produktSklepu.setSklad(skladProduktu);
    produktSklepu.setWaga(wagaProduktu);
    produktSklepu.setDataWaznosci(dataWaznosciProduktu);
}

std::string Sklep::getNazwa() {
    return nazwa;
}

std::string Sklep::getRodzaj() {
    return rodzaj;
}

std::string Sklep::getWielkosc() {
    return wielkosc;
}

Czlowiek Sklep::getKupujacy() {
    return kupujacy;
}

void Sklep::printProdukt() {
    std::cout << "Nazwa produktu: " << produktSklepu.getNazwa() << "\n";
    std::cout << "Ilosc produktu: " << produktSklepu.getIlosc() << "\n";
    std::cout << "Sklad produktu: " << produktSklepu.getSklad() << "\n";
    std::cout << "Waga produktu: " << produktSklepu.getWaga() << "\n";
    std::cout << "Data waznosci produktu: " << produktSklepu.getDataWaznosci() << "\n";
}

Sklep::Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc) {
    this->nazwa = nazwa;
    this->rodzaj = rodzaj;
    this->wielkosc = wielkosc;
};

Sklep::~Sklep() {}
