//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03
//  @ File Name : Sklep.h
//  @ Date : 22.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SKLEP_H)
#define _SKLEP_H

#include "Czlowiek.h"
#include "Produkt.h"

class Sklep {
public:
    void setNazwa(std::string nazwa);
	void setRodzaj(std::string rodzaj);
	void setWielkosc(std::string wielkosc);
	void setKupujacy(Czlowiek kupujacy);
	void setProdukt(std::string nazwa, int ilosc, std::string sklad, float waga, std::string dataWaznosci);
    std::string getNazwa();
    std::string getRodzaj();
    std::string getWielkosc();
    Czlowiek getKupujacy();
	void printProdukt();
    Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc, Czlowiek kupujacy);
    ~Sklep();
private:
    std::string nazwa;
    std::string rodzaj;
    std::string wielkosc;
    Czlowiek kupujacy;
    Produkt produktSklepu;
};

#endif  //_SKLEP_H
