//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : BernouliDiagram.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BERNOULIDIAGRAM_H)
#define _BERNOULIDIAGRAM_H

#include "BinomialTheorem.h"
#include "Power.h"

class BernouliDiagram {
public:

	/**
	 * Constructor
	 */
	BernouliDiagram();

	/**
	 * Destructor
	 */
	~BernouliDiagram();

	/**
	 * Calculates the Bernouli diagram recursively
	 *
	 * @param p The probability of success
	 * @param n The number of trials
	 * @param k The number of successes
	 *
	 * @return The Bernouli diagram
	 */
	long double bernouliDiagramRecursively(double p, int n, int k);

	/**
	 * Calculates the Bernouli diagram iteratively
	 *
	 * @param p The probability of success
	 * @param n The number of trials
	 * @param k The number of successes
	 *
	 * @return The Bernouli diagram
	 */
    long double bernouliDiagramIteratively(double p, int n, int k);

private:

	/**
	 * The probability of failure
	 */
	double q;

	/**
	 * The probability of success
	 */
	long double p;

	/**
	 * Pointer to the Power class
	 */
	Power * powerPtr;

	/**
	 * Pointer to the BinomialTheorem class
	 */
	BinomialTheorem * binomialTheoremPtr;
};

#endif  //_BERNOULIDIAGRAM_H
