//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : Factorial.h
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H

/**
 * Class representing the factorial
 */
class Factorial {
public:

	/**
	 * Calculates the factorial recursively
	 *
	 * @param n The number for which the factorial is calculated
	 *
	 * @return The factorial
	 */
	long double factorialRecursively(int n);

	/**
	 * Calculates the factorial iteratively
	 *
	 * @param n The number for which the factorial is calculated
	 *
	 * @return The factorial
	 */
	long double factorialIteratively(int n);
};

#endif  //_FACTORIAL_H
