//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 04b
//  @ File Name : Employee.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include "Employee.h"

string Employee::getFirstName() {
    return firstName;
}

void Employee::setFirstName(string firstName) {
    this->firstName = firstName;
}

string Employee::getLastName() {
    return lastName;
}

void Employee::setLastName(string lastName) {
    this->lastName = lastName;
}

string Employee::getPosition() {
    return position;
}

void Employee::setPosition(string position) {
    this->position = position;
}

string Employee::getSpecialization() {
    return specialization;
}

void Employee::setSpecialization(string specialization) {
    this->specialization = specialization;
}

int Employee::getExperience() {
    return experience;
}

void Employee::setExperience(int experience) {
    this->experience = experience;
}

Employee::Employee(string firstName, string lastName, string position, string specialization, int experience) {
    setFirstName(firstName);
    setLastName(lastName);
    setPosition(position);
    setSpecialization(specialization);
    setExperience(experience);
}

Employee::~Employee() {}

void Employee::earnMoreExperience() {
    cout << "Employee " << firstName << " " << lastName << " earned more experience." << endl;
    experience++;
}

void Employee::getPromoted() {
    cout << "Employee " << firstName << " " << lastName << " got promoted." << endl;
    position = "Senior " + position;
}

void Employee::getFired() {
    cout << "Employee " << firstName << " " << lastName << " got fired." << endl;
    position = "Unemployed";
}
