//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04b
//  @ File Name : Firma.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_FIRMA_H)
#define _FIRMA_H

#include <string>
#include <vector>
#include "Pracownik.h"

class Firma {
public:
    void setNazwa(std::string nazwa);
    void setSpecjalizacja(std::string specjalizacja);
    void setLatNaRynku(int latNaRynku);
    void setIloscPracownikow(int iloscPracownikow);
    void setRocznyPrzychod(int rocznyPrzychod);
    std::string getNazwa();
    std::string getSpecjalizacja();
    int getLatNaRynku();
    int getIloscPracownikow();
    int getRocznyPrzychod();
    Firma(std::string nazwa, std::string specjalizacja, int latNaRynku, int iloscPracownikow, int rocznyPrzychod);
    ~Firma();
	void dodajPracownika(Pracownik * pracownik);
	void usunPracownika(int i);
	void wyswietlPracownika(int i);
	void ustawPracownika(int i, std::string imiePracownika, std::string nazwiskoPracownika, std::string stanowiskoPracownika, std::string specjalizacjaPracownika, int doswiadczeniePracownika);
private:
    std::string nazwa;
    std::string specjalizacja;
    int latNaRynku;
    int iloscPracownikow;
    int rocznyPrzychod;
    std::vector<Pracownik *> pracownicy;
};

#endif  //_FIRMA_H
