//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04b
//  @ File Name : Pracownik.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H

#include <string>

class Pracownik {
public:
    void setImie(std::string imie);
    void setNazwisko(std::string nazwisko);
    void setStanowisko(std::string stanowisko);
    void setSpecjalizacja(std::string specjalizacja);
    void setDoswiadczenie(int doswiadczenie);
    std::string getImie();
    std::string getNazwisko();
    std::string getStanowisko();
    std::string getSpecjalizacja();
    int getDoswiadczenie();
    Pracownik(std::string imie, std::string nazwisko, std::string stanowisko, std::string specjalizacja, int doswiadczenie);
    ~Pracownik();
private:
    std::string imie;
    std::string nazwisko;
    std::string stanowisko;
    std::string specjalizacja;
    int doswiadczenie;
};

#endif  //_PRACOWNIK_H