//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08a
//  @ File Name : Shop.cpp
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>
#include "Shop.h"

using namespace std;

string Shop::getName() {
    return name;
}

void Shop::setName(string name) {
    this->name = name;
}

string Shop::getType() {
    return type;
}

void Shop::setType(string type) {
    this->type = type;
}

string Shop::getSize() {
    return size;
}

void Shop::setSize(string size) {
    this->size = size;
}

string Shop::getOpeningHours() {
    return openingHours;
}

void Shop::setOpeningHours(string openingHours) {
    this->openingHours = openingHours;
}

void Shop::setFlagshipProduct(Product * flagshipProduct) {
    this->flagshipProduct = flagshipProduct;
}

Product * Shop::getFlagshipProduct() {
    return flagshipProduct;
}

Shop::Shop(string name, string type, string size, string openingHours, Product * flagshipProduct) {
    setName(name);
    setType(type);
    setSize(size);
    setOpeningHours(openingHours);
    setFlagshipProduct(flagshipProduct);
}

Shop::~Shop() {}

void Shop::openShop() {
    cout << "Shop " << getName() << " is open!" << endl;
}

void Shop::printFlagshipProduct() {
    cout << "Shop flagship product: " << getFlagshipProduct()->getName() << endl;
}

void Shop::closeShop() {
    cout << "Shop " << getName() << " is closed!" << endl;
}
