//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 05c
//  @ File Name : Company.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>

#include "Company.h"

using namespace std;

string Company::getName() {
    return name;
}

void Company::setName(string name) {
    this->name = name;
}

string Company::getSpecialization() {
    return specialization;
}

void Company::setSpecialization(string specialization) {
    this->specialization = specialization;
}

int Company::getYearsOnTheMarket() {
    return yearsOnTheMarket;
}

void Company::setYearsOnTheMarket(int yearsOnTheMarket) {
    this->yearsOnTheMarket = yearsOnTheMarket;
}

int Company::getNumberOfEmployees() {
    return numberOfEmployees;
}

void Company::setNumberOfEmployees(int numberOfEmployees) {
    this->numberOfEmployees = numberOfEmployees;
}

int Company::getAnnualRevenue() {
    return annualRevenue;
}

void Company::setAnnualRevenue(int annualRevenue) {
    this->annualRevenue = annualRevenue;
}

Company::Company(string name, string specialization, int yearsOnTheMarket, int numberOfEmployees, int annualRevenue) {
    setName(name);
    setSpecialization(specialization);
    setYearsOnTheMarket(yearsOnTheMarket);
    setNumberOfEmployees(numberOfEmployees);
    setAnnualRevenue(annualRevenue);
}

Company::~Company() {}

void Company::hireEmployee() {
    cout << "Hiring employee..." << endl;
}

void Company::earnMoney() {
    cout << "Earning money..." << endl;
    annualRevenue += 1000000;
}

void Company::fireEmployee() {
    cout << "Firing employee..." << endl;
}

void Company::attachShop(Shop * shop) {
    shops.push_back(shop);
    cout << "Shop " << shop->getName() << " attached to " << name << endl;
}

void Company::detachShop(Shop * shop) {
    for (int i = 0; i < shops.size(); i++) {
        if (shops[i] == shop) {
            shops.erase(shops.begin() + i);
            break;
        }
    }
    cout << "Shop " << shop->getName() << " detached from " << name << endl;
}

void Company::printShop(Shop * shop) {
    shop->printShop();
}
