//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 05c
//  @ File Name : Shop.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include <string>

#include "Shop.h"

using namespace std;

string Shop::getName() {
    return name;
}

void Shop::setName(string name) {
    this->name = name;
}

string Shop::getType() {
    return type;
}

void Shop::setType(string type) {
    this->type = type;
}

string Shop::getSize() {
    return size;
}

void Shop::setSize(string size) {
    this->size = size;
}

string Shop::getOpeningHours() {
    return openingHours;
}

void Shop::setOpeningHours(string openingHours) {
    this->openingHours = openingHours;
}

Shop::Shop(string name, string type, string size, string openingHours, Building * building) {
    setName(name);
    setType(type);
    setSize(size);
    setOpeningHours(openingHours);
    this->building = building;
}

Shop::~Shop() {}

void Shop::openShop() {
    cout << "Shop " << getName() << " is open!" << endl;
}

void Shop::printShop() {
    cout << "Name: " << getName() << endl;
    cout << "Type: " << getType() << endl;
    cout << "Size: " << getSize() << endl;
    cout << "Opening hours: " << getOpeningHours() << endl;
    cout << "Building: " << endl;
    building->printBuilding();
}

void Shop::closeShop() {
    cout << "Shop " << getName() << " is closed!" << endl;
}
