//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08c
//  @ File Name : Factorial.cpp
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "Factorial.h"

long double Factorial::factorialRecursively(int n) {
    if (n == 0) return 1;
    else return n * factorialRecursively(n - 1);
}

long double Factorial::factorialIteratively(int n) {
    long double result = 1;
    for (int i = 1; i <= n; i++) result *= i;
    return result;
}
