//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 04a
//  @ File Name : CareTaker.h
//  @ Date : 29.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_CARETAKER_H)
#define _CARETAKER_H

#include <string>
#include <vector>
#include "Cat.h"

using namespace std;

class CareTaker {
public:
    string getName();
    void setName(string name);
    float getHeight();
    void setHeight(float height);
    int getAge();
    void setAge(int age);
    string getHobby();
    void setHobby(string hobby);
    bool getCanTakeCareOfCat();
    void setCanTakeCareOfCat(bool canTakeCareOfCat);
    CareTaker(string name, float height, int age, string hobby, bool canTakeCareOfCat);
    ~CareTaker();
    void takeCareOfYourHobby();
    void goShopping();
	void attachCat(Cat * cat);
	void detachCat(Cat * cat);
    void printCat(Cat * cat);
private:
	string name;
	float height;
	int age;
	string hobby;
	bool canTakeCareOfCat;
    vector <Cat *> cats;
};

#endif  //_CARETAKER_H
