//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04a
//  @ File Name : Kot.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "Kot.h"

void Kot::setImie(std::string imie) {
    this->imie = imie;
}

void Kot::setKolor(std::string kolor) {
    this->kolor = kolor;
}

void Kot::setWiek(int wiek) {
    this->wiek = wiek;
}

void Kot::setPoglaskany(bool mozeZajacSieKotem, bool poglaskany) {
    if((poglaskany) && (mozeZajacSieKotem)) {
        this->poglaskany = true;
    } else {
        this->poglaskany = false;
    }
}

void Kot::setNajedzony(bool mozeZajacSieKotem, bool najedzony) {
    if((najedzony) && (mozeZajacSieKotem)) {
        this->najedzony = true;
    } else {
        this->najedzony = false;
    }
}

std::string Kot::getImie() {
    return imie;
}

std::string Kot::getKolor() {
    return kolor;
}

int Kot::getWiek() {
    return wiek;
}

bool Kot::getPoglaskany() {
    return poglaskany;
}

bool Kot::getNajedzony() {
    return najedzony;
}

Kot::Kot(std::string imie, std::string kolor, int wiek, bool poglaskany, bool najedzony) {
    this->imie = imie;
    this->kolor = kolor;
    this->wiek = wiek;
    this->poglaskany = poglaskany;
    this->najedzony = najedzony;
}

Kot::~Kot() {}

void Kot::dajSiePoglskac(std::string imieOsoby) {
    std::cout << imieOsoby << " glaszcze " << getImie()  << "!\n";
}

void Kot::zamiaucz() {
    std::cout << getImie() << ": Miau! \n";
}

void Kot::zamrucz() {
    std::cout << getImie() << ": Mrrrrr! \n";
}