//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04a
//  @ File Name : Opiekun.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "Opiekun.h"


void Opiekun::setImie(std::string imie) {
    this->imie = imie;
}

void Opiekun::setWzrost(float wzrost) {
    this->wzrost = wzrost;
}

void Opiekun::setWiek(int wiek) {
    this->wiek = wiek;
}

void Opiekun::setHobby(std::string hobby) {
    this->hobby = hobby;
}

void Opiekun::setMozeZajacSieKotem(bool mozeZajacSieKotem) {
    this->mozeZajacSieKotem = mozeZajacSieKotem;
}

std::string Opiekun::getImie() {
    return imie;
}

float Opiekun::getWzrost() {
    return wzrost;
}

int Opiekun::getWiek() {
    return wiek;
}

std::string Opiekun::getHobby() {
    return hobby;
}

bool Opiekun::getMozeZajacSieKotem() {
    return mozeZajacSieKotem;
}

Opiekun::Opiekun(std::string imie, float wzrost, int wiek, std::string hobby, bool mozeZajacSieKotem) {
    this->imie = imie;
    this->wzrost = wzrost;
    this->wiek = wiek;
    this->hobby = hobby;
    this->mozeZajacSieKotem = mozeZajacSieKotem;
}

Opiekun::~Opiekun() {}

void Opiekun::zajmijSieSwoimHobby() {
    std::cout << getImie() << " zajmuje sie swoim hobby. \n";
}

void Opiekun::zrobZakupy() {
    std::cout << getImie() << " robi zakupy. \n";
}

void Opiekun::dodajKota(Kot * kot) {
    koty.push_back(kot);
}

void Opiekun::usunKota(int i) {
    koty.pop_back();
}

void Opiekun::wyswietlKota(int i) {
    std::cout << "Imie: " << koty[i]->getImie() << ", Kolor: " << koty[i]->getKolor() << ", Wiek: " << koty[i]->getWiek() << "\n";
    std::cout << "Poglaskany: " << koty[i]->getPoglaskany() << ", Najedzony: " << koty[i]->getNajedzony() << "\n";
}

void Opiekun::ustawKota(int i, std::string imieKota, std::string kolorKota, int wiekKota, bool czyPoglaskany, bool czyNajedzony) {
    Kot * kot = new Kot(imieKota, kolorKota, wiekKota, czyPoglaskany, czyNajedzony);
    koty[i] = kot;
}