//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04a
//  @ File Name : Opiekun.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_OPIEKUN_H)
#define _OPIEKUN_H

#include <string>
#include <vector>
#include "Kot.h"

class Opiekun {
public:
    void setImie(std::string imie);
    void setWzrost(float wzrost);
    void setWiek(int wiek);
    void setHobby(std::string hobby);
    void setMozeZajacSieKotem(bool mozeZajacSieKotem);
    std::string getImie();
    float getWzrost();
    int getWiek();
    std::string getHobby();
    bool getMozeZajacSieKotem();
    Opiekun(std::string imie, float wzrost, int wiek, std::string hobby, bool mozeZajacSieKotem);
    ~Opiekun();
    void zajmijSieSwoimHobby();
    void zrobZakupy();
	void dodajKota(Kot * kot);
	void usunKota(int i);
	void wyswietlKota(int i);
	void ustawKota(int i, std::string imieKota, std::string kolorKota, int wiekKota, bool czyPoglaskany, bool czyNajedzony);
private:
    std::string imie;
	float wzrost;
	int wiek;
    std::string hobby;
	bool mozeZajacSieKotem;
    std::vector<Kot *> koty;
};

#endif  //_OPIEKUN_H
