//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 04c
//  @ File Name : Shop.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_SHOP_H)
#define _SHOP_H

#include <string>
#include <vector>
#include "Product.h"

using namespace std;

class Shop {
public:
    string getName();
	void setName(string name);
    string getType();
	void setType(string type);
    string getSize();
	void setSize(string size);
    string getOpeningHours();
	void setOpeningHours(string openingHours);
    Product * getFlagshipProduct();
	void setFlagshipProduct(Product * flagshipProduct);
	Shop(string name, string type, string size, string openingHours, Product * flagshipProduct);
	~Shop();
	void openShop();
	void printFlagshipProduct();
	void closeShop();
    void attachProduct(Product * product);
    void detachProduct(Product * product);
    void printProduct(Product * product);
private:
	string name;
	string type;
	string size;
	string openingHours;
	Product * flagshipProduct;
    vector <Product *> products;
};

#endif  //_SHOP_H
