//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03d
//  @ File Name : Sklep.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include <iostream>
#include "Sklep.h"

void Sklep::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Sklep::setRodzaj(std::string rodzaj) {
    this->rodzaj = rodzaj;
}

void Sklep::setWielkosc(std::string wielkosc) {
    this->wielkosc = wielkosc;
}

void Sklep::setGodzinyOtwarcia(std::string godzinyOtwarcia) {
    this->godzinyOtwarcia = godzinyOtwarcia;
}

void Sklep::setProdukt(std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu) {
    Produkt produkt = Produkt(nazwaProduktu, iloscProduktu, skladProduktu, wagaProduktu, dataWaznosciProduktu);
}

std::string Sklep::getNazwa() {
    return nazwa;
}

std::string Sklep::getRodzaj() {
    return rodzaj;
}

std::string Sklep::getWielkosc() {
    return wielkosc;
}

std::string Sklep::getGodzinyOtwarcia() {
    return godzinyOtwarcia;
}

void Sklep::printProdukt() {
    std::cout << "Nazwa: " << produktSklepu.getNazwa() << ", Rodzaj: " << produktSklepu.getIlosc() << ", Sklad: " << produktSklepu.getSklad() << "\n";
    std::cout << "Waga: " << produktSklepu.getWaga() << ", Data waznosci: " << produktSklepu.getDataWaznosci() << "\n";
}

Sklep::Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc, std::string godzinyOtwarcia,
             Produkt produktSklepu) : produktSklepu(produktSklepu) {
    this->nazwa = nazwa;
    this->rodzaj = rodzaj;
    this->wielkosc = wielkosc;
    this->godzinyOtwarcia = godzinyOtwarcia;
}

Sklep::~Sklep() {}

void Sklep::dodajProdukt(Produkt * produkt) {
    produkty.push_back(produkt);
}

void Sklep::usunProdukt(int i) {
    produkty.pop_back();
}

void Sklep::wyswietlProdukt(int i) {
    std::cout << "Nazwa: " << produkty[i]->getNazwa() << ", Ilosc: " << produkty[i]->getIlosc() << ", Sklad: " << produkty[i]->getSklad() << "\n";
    std::cout << "Waga: " << produkty[i]->getWaga() << ", Data waznosci: " << produkty[i]->getDataWaznosci() << "\n";
}

void Sklep::ustawProdukt(int i, std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu) {
    Produkt * produkt = new Produkt(nazwaProduktu, iloscProduktu, skladProduktu, wagaProduktu, dataWaznosciProduktu);
    produkty[i] = produkt;
}
