//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 04c
//  @ File Name : Sklep.h
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SKLEP_H)
#define _SKLEP_H

#include <vector>
#include "Produkt.h"

class Sklep {
public:
    void setNazwa(std::string nazwa);
    void setRodzaj(std::string rodzaj);
    void setWielkosc(std::string wielkosc);
    void setGodzinyOtwarcia(std::string godzinyOtwarcia);
    void setProdukt(std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu);
    std::string getNazwa();
    std::string getRodzaj();
    std::string getWielkosc();
    std::string getGodzinyOtwarcia();
    void printProdukt();
    Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc, std::string godzinyOtwarcia,
          Produkt produktSklepu);
    ~Sklep();
	void dodajProdukt(Produkt * produkt);
	void usunProdukt(int i);
	void wyswietlProdukt(int i);
	void ustawProdukt(int i, std::string nazwaProduktu, int iloscProduktu, std::string skladProduktu, float wagaProduktu, std::string dataWaznosciProduktu);
private:
	std::string nazwa;
	std::string rodzaj;
	std::string wielkosc;
	std::string godzinyOtwarcia;
	Produkt produktSklepu;
	std::vector<Produkt *> produkty;
};

#endif  //_SKLEP_H