//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03b
//  @ File Name : UniversitySubject.h
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_UNIVERSITYSUBJECT_H)
#define _UNIVERSITYSUBJECT_H

#include <string>

using namespace std;

/**
 * Class representing a university subject
 */
class UniversitySubject {
public:
	/**
	 * Gets the name of the university subject
	 *
	 * @return The name of the university subject
	 */
	string getName();

	/**
	 * Sets the name of the university subject
	 *
	 * @param name The name of the university subject
	 */
	void setName(string name);

	/**
	 * Gets the description of the university subject
	 *
	 * @return The description of the university subject
	 */
	string getDescription();

	/**
	 * Sets the description of the university subject
	 *
	 * @param description The description of the university subject
	 */
	void setDescription(string description);

	/**
	 * Gets the ETCS points of the university subject
	 *
	 * @return The ETCS points of the university subject
	 */
	float getETCSPoints();

	/**
	 * Sets the ETCS points of the university subject
	 *
	 * @param ETCSPoints The ETCS points of the university subject
	 */
	void setETCSPoints(float ETCSPoints);

	/**
	 * Gets the lecturer of the university subject
	 *
	 * @return The lecturer of the university subject
	 */
	string getLecturer();

	/**
	 * Sets the lecturer of the university subject
	 *
	 * @param lecturer The lecturer of the university subject
	 */
	void setLecturer(string lecturer);

	/**
	 * Gets the number of unassisted work hours of the university subject
	 *
	 * @return The number of unassisted work hours of the university subject
	 */
	int getNumberOfUnassistedWorkHours();

	/**
	 * Sets the number of unassisted work hours of the university subject
	 *
	 * @param numberOfUnassistedWorkHours The number of unassisted work hours of the university subject
	 */
	void setNumberOfUnassistedWorkHours(int numberOfUnassistedWorkHours);

	/**
	 * Constructor
	 *
	 * @param name The name of the university subject
	 * @param description The description of the university subject
	 * @param ETCSPoints The ETCS points of the university subject
	 * @param lecturer The lecturer of the university subject
	 * @param numberOfUnassistedWorkHours The number of unassisted work hours of the university subject
	 */
	UniversitySubject(string name, string description, float ETCSPoints, string lecturer, int numberOfUnassistedWorkHours);

	/**
	 * Destructor
	 */
	~UniversitySubject();

	/**
	 * Prints the description of the university subject
	 */
	void printDescription();

	/**
	 * Prints the lecturer of the university subject
	 */
	void printLecturer();

	/**
	 * Prints the number of unassisted work hours of the university subject
	 */
	void printNumberOfUnassistedWorkHours();

private:

	/**
	 * The name of the university subject
	 */
	string name;

	/**
	 * The description of the university subject
	 */
	string description;

	/**
	 * The ETCS points of the university subject
	 */
	float ETCSPoints;

	/**
	 * The lecturer of the university subject
	 */
	string lecturer;

	/**
	 * The number of unassisted work hours of the university subject
	 */
	int numberOfUnassistedWorkHours;
};

#endif  //_UNIVERSITYSUBJECT_H
