//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : BernouliDiagram.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BERNOULIDIAGRAM_H)
#define _BERNOULIDIAGRAM_H

#include "BinomialTheorem.h"
#include "Power.h"

class BernouliDiagram {
public:
    long double bernouliDiagram(double p, int n, int k);
    BernouliDiagram();
    ~BernouliDiagram();
private:
	double q;
	long double p;
	Power * powerPtr;
	BinomialTheorem * binomialTheoremPtr;
};

#endif  //_BERNOULIDIAGRAM_H
