//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : BernouliDiagram.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "BernouliDiagram.h"

BernouliDiagram::BernouliDiagram() {
    binomialTheoremPtr = new BinomialTheorem();
    powerPtr = new Power();
}

BernouliDiagram::~BernouliDiagram() {
    delete binomialTheoremPtr;
    delete powerPtr;
}

long double BernouliDiagram::bernouliDiagram(double p, int n, int k) {
    q = 1 - p;
    return ((binomialTheoremPtr->binominalTheorem(n, k)) * (powerPtr->power(p, k)) * powerPtr->power(q, n - k));
}
