//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : Factorial.cpp
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "Factorial.h"

long double Factorial::factorial(int n) {
    if (n == 0) {
        return 1;
    } else {
        return n * factorial(n - 1);
    }
}
