//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : Factorial.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H

class Factorial {
public:
	long double factorial(int n);
};

#endif  //_FACTORIAL_H
