//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 07
//  @ File Name : Power.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_POWER_H)
#define _POWER_H

class Power {
public:
	double power(double base, int exponent);
};

#endif  //_POWER_H
