//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 02
//  @ File Name : Dachshund.h
//  @ Date : 17.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_DACHSHUND_H)
#define _DACHSHUND_H

#include <string>

#include "Dog.h"

using namespace std;

/**
 * Class representing a dachshund
 */
class Dachshund : public Dog {
public:

	/**
	 * Gets the name of the dachshund
	 *
	 * @return The name of the dachshund
	 */
	string getName();

	/**
	 * Sets the name of the dachshund
	 *
	 * @param name The name of the dachshund
	 */
	void setName(string name);

	/**
	 * Constructor
	 *
	 * @param age The age of the dachshund
	 * @param color The color of the dachshund
	 * @param height The height of the dachshund
	 * @param weight The weight of the dachshund
	 * @param landAnimal Whether the dachshund is a land animal
	 * @param purpose The purpose of the dachshund
	 * @param personality The personality of the dachshund
	 * @param longHaired Whether the dachshund is long-haired
	 * @param name The name of the dachshund
	 */
	Dachshund(
		int age,
		string color,
		float height,
		float weight,
		bool landAnimal,
		string purpose,
        string personality,
		bool longHaired,
		string name
	);

	/**
	 * Destructor
	 */
	~Dachshund();

private:

	/**
	 * The name of the dachshund
	 */
	string name;
};

#endif  //_DACHSHUND_H
