//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 02
//  @ File Name : Dog.h
//  @ Date : 17.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_DOG_H)
#define _DOG_H

#include <string>

#include "Mammal.h"

using namespace std;

/**
 * Class representing a dog
 */
class Dog : public Mammal {
public:

	/**
	 * Gets the purpose of the dog
	 *
	 * @return The purpose of the dog
	 */
	string getPurpose();

	/**
	 * Sets the purpose of the dog
	 *
	 * @param purpose The purpose of the dog
	 */
	void setPurpose(string purpose);

	/**
	 * Gets the personality of the dog
	 *
	 * @return The personality of the dog
	 */
	string getPersonality();

	/**
	 * Sets the personality of the dog
	 *
	 * @param personality The personality of the dog
	 */
	void setPersonality(string personality);

	/**
	 * Gets whether the dog is long-haired
	 *
	 * @return Whether the dog is long-haired
	 */
	bool getLongHaired();

	/**
	 * Sets whether the dog is long-haired
	 *
	 * @param longHaired Whether the dog is long-haired
	 */
	void setLongHaired(bool longHaired);

	/**
	 * Constructor
	 *
	 * @param age The age of the dog
	 * @param color The color of the dog
	 * @param height The height of the dog
	 * @param weight The weight of the dog
	 * @param landAnimal Whether the dog is a land animal
	 * @param purpose The purpose of the dog
	 * @param personality The personality of the dog
	 * @param longHaired Whether the dog is long-haired
	 */
	Dog(
		int age,
		string color,
		float height,
		float weight,
		bool landAnimal,
		string purpose,
		string personality,
        bool longHaired
	);

	/**
	 * Destructor
	 */
	~Dog();

private:

	/**
	 * The purpose of the dog
	 */
	string purpose;

	/**
	 * The personality of the dog
	 */
	string personality;

	/**
	 * Whether the dog is long-haired
	 */
	bool longHaired;
};

#endif  //_DOG_H
