//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 02
//  @ File Name : Mammal.cpp
//  @ Date : 17.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "Mammal.h"

#include <string>

using namespace std;

int Mammal::getAge() {
    return age;
}

void Mammal::setAge(int age) {
    this->age = age;
}

string Mammal::getColor() {
    return color;
}

void Mammal::setColor(string color) {
    this->color = color;
}

float Mammal::getHeight() {
    return height;
}

void Mammal::setHeight(float height) {
    this->height = height;
}

float Mammal::getWeight() {
    return weight;
}

void Mammal::setWeight(float weight) {
    this->weight = weight;
}

bool Mammal::getLandAnimal() {
    return landAnimal;
}

void Mammal::setLandAnimal(bool landAnimal) {
    this->landAnimal = landAnimal;
}

Mammal::Mammal(int age, string color, float height, float weight, bool landAnimal) {
    setAge(age);
    setColor(color);
    setHeight(height);
    setWeight(weight);
    setLandAnimal(landAnimal);
}

Mammal::~Mammal() {}
