//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 03c
//  @ File Name : Employee.h
//  @ Date : 24.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_EMPLOYEE_H)
#define _EMPLOYEE_H

#include <string>

using namespace std;

class Employee {
public:
	string getFirstName();
	void setFirstName(string firstName);
	string getLastName();
	void setLastName(string lastName);
	string getPosition();
	void setPosition(string position);
	string getSpecialization();
	void setSpecialization(string specialization);
	int getExperience();
	void setExperience(int experience);
	Employee(string firstName, string lastName, string position, string specialization, int experience);
    ~Employee();
    void earnMoreExperience();
    void getPromoted();
    void getFired();
private:
	string firstName;
	string lastName;
	string position;
	string specialization;
	int experience;
};

#endif  //_EMPLOYEE_H
