//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03c
//  @ File Name : Firma.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Firma.h"

void Firma::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Firma::setSpecjalizacja(std::string specjalizacja) {
    this->specjalizacja = specjalizacja;
}

void Firma::setLatNaRynku(int latNaRynku) {
    this->latNaRynku = latNaRynku;
}

void Firma::setIloscPracownikow(int iloscPracownikow) {
    this->iloscPracownikow = iloscPracownikow;
}

void Firma::setRocznyPrzychod(int rocznyPrzychod) {
    this->rocznyPrzychod = rocznyPrzychod;
}

std::string Firma::getNazwa() {
    return nazwa;
}

std::string Firma::getSpecjalizacja() {
    return specjalizacja;
}

int Firma::getLatNaRynku() {
    return latNaRynku;
}

int Firma::getIloscPracownikow() {
    return iloscPracownikow;
}

int Firma::getRocznyPrzychod() {
    return rocznyPrzychod;
}

Firma::Firma(std::string nazwa, std::string specjalizacja, int latNaRynku, int iloscPracownikow, int rocznyPrzychod) {
    this->nazwa = nazwa;
    this->specjalizacja = specjalizacja;
    this->latNaRynku = latNaRynku;
    this->iloscPracownikow = iloscPracownikow;
    this->rocznyPrzychod = rocznyPrzychod;
}

Firma::~Firma() {}
