//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 03c
//  @ File Name : Pracownik.cpp
//  @ Date : 29.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Pracownik.h"

void Pracownik::setImie(std::string imie) {
    this->imie = imie;
}

void Pracownik::setNazwisko(std::string nazwisko) {
    this->nazwisko = nazwisko;
}

void Pracownik::setStanowisko(std::string stanowisko) {
    this->stanowisko = stanowisko;
}

void Pracownik::setSpecjalizacja(std::string specjalizacja) {
    this->specjalizacja = specjalizacja;
}

void Pracownik::setDoswiadczenie(int doswiadczenie) {
    this->doswiadczenie = doswiadczenie;
}

std::string Pracownik::getImie() {
    return imie;
}

std::string Pracownik::getNazwisko() {
    return nazwisko;
}

std::string Pracownik::getStanowisko() {
    return stanowisko;
}

std::string Pracownik::getSpecjalizacja() {
    return specjalizacja;
}

int Pracownik::getDoswiadczenie() {
    return doswiadczenie;
}

Pracownik::Pracownik(std::string imie, std::string nazwisko, std::string stanowisko, std::string specjalizacja, int doswiadczenie) {
    this->imie = imie;
    this->nazwisko = nazwisko;
    this->stanowisko = stanowisko;
    this->specjalizacja = specjalizacja;
    this->doswiadczenie = doswiadczenie;
}

Pracownik::~Pracownik() {}
