//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 02
//  @ File Name : Dog.h
//  @ Date : 17.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_DOG_H)
#define _DOG_H

#include <string>
#include "Mammal.h"

using namespace std;

class Dog : public Mammal {
public:
	string getPurpose();
	void setPurpose(string purpose);
	string getPersonality();
	void setPersonality(string personality);
	bool getLongHaired();
	void setLongHaired(bool longHaired);
	Dog(int age, string color, float height, float weight, bool landAnimal, string purpose, string personality,
        bool longHaired);
	~Dog();
private:
	string purpose;
	string personality;
	bool longHaired;
};

#endif  //_DOG_H
