//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Jamnik.h
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
public:
	Jamnik(string imie, string kolorSiersci);
	void setImie(string imie);
	void setKolorSiersci(string kolorSiersci);
	string getImie();
	string getKolorSiersci();
	~Jamnik();
private:
	string imie;
	string kolorSiersci;
};

#endif  //_JAMNIK_H
