//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Jamnik.cpp
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Jamnik.h"

Jamnik::Jamnik(std::string przeznaczenie, bool umieSztuczki, bool dlugowlosy, std::string charakter,
               std::string imie, std::string kolorSiersci) : Pies(0, 0, 0, 0, przeznaczenie, umieSztuczki, dlugowlosy,
                                                                  charakter) {
    this->imie = imie;
    this->kolorSiersci = kolorSiersci;
}

Jamnik::~Jamnik() {}

void Jamnik::setImie(std::string imie) {
    this->imie = imie;
}

void Jamnik::setKolorSiersci(std::string kolorSiersci) {
    this->kolorSiersci = kolorSiersci;
}

std::string Jamnik::getImie() {
    return imie;
}

std::string Jamnik::getKolorSiersci() {
    return kolorSiersci;
}
