//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 02
//  @ File Name : Mammal.h
//  @ Date : 17.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_MAMMAL_H)
#define _MAMMAL_H

#include <string>

using namespace std;

class Mammal {
public:
	int getAge();
	void setAge(int age);
	string getColor();
	void setColor(string color);
	float getHeight();
	void setHeight(float height);
	float getWeight();
	void setWeight(float weight);
	bool getLandAnimal();
	void setLandAnimal(bool landAnimal);
	Mammal(int age, string color, float height, float weight, bool landAnimal);
	~Mammal();
private:
	int age;
	string color;
	float height;
	float weight;
	bool landAnimal;
};

#endif  //_MAMMAL_H
