//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Pies.h
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	Pies(string przeznaczenie, bool umieSztuczki, bool dlugowlosy, string charakter);
	void setPrzeznaczenie(string przeznaczenie);
	void setUmieSztuczki(bool umieSztuczki);
	void setDlugowlosy(bool dlugowlosy);
	void setCharakter(string charakter);
	string getPrzeznaczenie();
	bool getUmieSztuczki();
	bool getDlugowlosy();
	string getCharakter();
	~Pies();
private:
	string przeznaczenie;
	bool umieSztuczki;
	bool dlugowlosy;
	string charakter;
};

#endif  //_PIES_H
