//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Pies.h
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include <string>
#include "Ssak.h"

class Pies : public Ssak {
public:
	Pies(std::string przeznaczenie, bool umieSztuczki, bool dlugowlosy, std::string charakter);
	void setPrzeznaczenie(std::string przeznaczenie);
	void setUmieSztuczki(bool umieSztuczki);
	void setDlugowlosy(bool dlugowlosy);
	void setCharakter(std::string charakter);
    std::string getPrzeznaczenie();
	bool getUmieSztuczki();
	bool getDlugowlosy();
    std::string getCharakter();
	~Pies();
private:
    std::string przeznaczenie;
	bool umieSztuczki;
	bool dlugowlosy;
    std::string charakter;
};

#endif  //_PIES_H
