//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Pies.cpp
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Pies.h"

Pies::Pies(std::string przeznaczenie, bool umieSztuczki, bool dlugowlosy, std::string charakter) {
    this->przeznaczenie = przeznaczenie;
    this->umieSztuczki = umieSztuczki;
    this->dlugowlosy = dlugowlosy;
    this->charakter = charakter;
}

Pies::~Pies() {}

void Pies::setPrzeznaczenie(std::string przeznaczenie) {
    this->przeznaczenie = przeznaczenie;
}

void Pies::setUmieSztuczki(bool umieSztuczki) {
    this->umieSztuczki = umieSztuczki;
}

void Pies::setDlugowlosy(bool dlugowlosy) {
    this->dlugowlosy = dlugowlosy;
}

void Pies::setCharakter(std::string charakter) {
    this->charakter = charakter;
}

std::string Pies::getPrzeznaczenie() {
    return przeznaczenie;
}

bool Pies::getUmieSztuczki() {
    return umieSztuczki;
}

bool Pies::getDlugowlosy() {
    return dlugowlosy;
}

std::string Pies::getCharakter() {
    return charakter;
}
