//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Pies.cpp
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Pies.h"

Pies::Pies(string przeznaczenie, bool umieSztuczki, bool dlugowlosy, string charakter) {
    this.przeznaczenie = przeznaczenie;
    this.umieSztuczki = umieSztuczki;
    this.dlugowlosy = dlugowlosy;
    this charakter = charakter;
}

Pies::~Pies() {}

void Pies::setPrzeznaczenie(string przeznaczenie) {
    this.przeznaczenie = przeznaczenie;
}

void Pies::setUmieSztuczki(bool umieSztuczki) {
    this.umieSztuczki = umieSztuczki;
}

void Pies::setDlugowlosy(bool dlugowlosy) {
    this.dlugowlosy = dlugowlosy;
}

void Pies::setCharakter(string charakter) {
    this.charakter = charakter;
}

string Pies::getPrzeznaczenie() {
    return przeznaczenie;
}

bool Pies::getUmieSztuczki() {
    return umieSztuczki;
}

bool Pies::getDlugowlosy() {
    return dlugowlosy;
}

string Pies::getCharakter() {
    return charakter;
}

