//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Ssak.h
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	Ssak(int umaszczenie, float wzrost, float waga, int wiek);
	void setUmaszczenie(int umaszczenie);
	void setWzrost(float wzrost);
	void setWaga(float waga);
	void setWiek(int wiek);
	int getUmaszczenie();
	float getWzrost();
	float getWaga();
	int getWiek();
	~Ssak();
private:
	int umaszczenie;
	float wzrost;
	float waga;
	int wiek;
};

#endif  //_SSAK_H
