//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab02
//  @ File Name : Ssak.cpp
//  @ Date : 09.03.2023
//  @ Author : Tomasz Wnuk
//
//


#include "Ssak.h"

Ssak::Ssak(int umaszczenie, float wzrost, float waga, int wiek) {
    this->umaszczenie = umaszczenie;
    this->wzrost = wzrost;
    this->waga = waga;
    this->wiek = wiek;
}

Ssak::~Ssak() {}

void Ssak::setUmaszczenie(int umaszczenie) {
    this->umaszczenie = umaszczenie;
}

void Ssak::setWzrost(float wzrost) {
    this->wzrost = wzrost;
}

void Ssak::setWaga(float waga) {
    this->waga = waga;
}

void Ssak::setWiek(int wiek) {
    this->wiek = wiek;
}

int Ssak::getUmaszczenie() {
    return umaszczenie;
}

float Ssak::getWzrost() {
    return wzrost;
}

float Ssak::getWaga() {
    return waga;
}

int Ssak::getWiek() {
    return wiek;
}

