//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 05c
//  @ File Name : Budynek.h
//  @ Date : 30.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_BUDYNEK_H)
#define _BUDYNEK_H

#include <string>

class Budynek {
public:
	void setAdres(std::string adres);
	void setIloscKas(int iloscKas);
	void setWielkosc(int wielkosc);
	void setKlimatyzowany(bool klimatyzowany);
	void setKosztUtrzymania(float kosztUtrzymania);
    std::string getAdres();
	int getIloscKas();
	int getWielkosc();
	bool getKlimatyzowany();
	float getKosztUtrzymania();
	Budynek(std::string adres, int iloscKas, int wielkosc, bool klimatyzowany, float kosztUtrzymania);
	~Budynek();
	void printBudynek();
	void zaplacRachunki();
	void posprzatajBudynek();
private:
    std::string adres;
	int iloscKas;
	int wielkosc;
	bool klimatyzowany;
	float kosztUtrzymania;
};

#endif  //_BUDYNEK_H
