//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 05c
//  @ File Name : Building.h
//  @ Date : 30.05.2023
//  @ Author : Tomasz Wnuk
//
//

#if !defined(_BUILDING_H)
#define _BUILDING_H

#include <string>

using namespace std;

class Building {
public:
	string getAddress();
	void setAddress(string address);
	int getSize();
	void setSize(int size);
	float getMaintenanceCost();
	void setMaintenanceCost(float maintenanceCost);
	bool getIsItAirConditioned();
	void setIsItAirConditioned(bool isItAirConditioned);
	int getNumberOfCashRegisters();
	void setNumberOfCashRegisters(int numberOfCashRegisters);
	Building(string address, int size, float maintenanceCost, bool isItAirConditioned, int numberOfCashRegisters);
	~Building();
	void payBills();
	void cleanBuilding();
	void printBuilding();
private:
	string address;
	int size;
	float maintenanceCost;
	bool isItAirConditioned;
	int numberOfCashRegisters;
};

#endif  //_BUILDING_H
