//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 05c
//  @ File Name : Firma.cpp
//  @ Date : 30.03.2023
//  @ Author : Tomasz Wnuk
//
//

#include <iostream>
#include "Firma.h"

void Firma::setNazwa(std::string nazwa) {
    this->nazwa = nazwa;
}

void Firma::setSzefFirmy(std::string szefFirmy) {
    this->szefFirmy = szefFirmy;
}

void Firma::setLatNaRynku(int latNaRynku) {
    this->latNaRynku = latNaRynku;
}

void Firma::setRocznyPrzychod(int rocznyPrzychod) {
    this->rocznyPrzychod = rocznyPrzychod;
}

void Firma::setIloscPracownikow(int iloscPracownikow) {
    this->iloscPracownikow = iloscPracownikow;
}

std::string Firma::getNazwa() {
    return nazwa;
}

std::string Firma::getSzefFirmy() {
    return szefFirmy;
}

int Firma::getLatNaRynku() {
    return latNaRynku;
}

int Firma::getRocznyPrzychod() {
    return rocznyPrzychod;
}

int Firma::getIloscPracownikow() {
    return iloscPracownikow;
}

Firma::Firma(std::string nazwa, std::string szefFirmy, int latNaRynku, int rocznyPrzychod, int iloscPracownikow) {
    this->nazwa = nazwa;
    this->szefFirmy = szefFirmy;
    this->latNaRynku = latNaRynku;
    this->rocznyPrzychod = rocznyPrzychod;
    this->iloscPracownikow = iloscPracownikow;
}

Firma::~Firma() {}

void Firma::dodajSklep(Sklep * sklep) {
    sklepy.push_back(sklep);
}

void Firma::usunSklep(string nazwaSklepu) {
    for(vector<person>::iterator it = sklepy.begin(); it != sklepy.end(); it++) {
        if(it->getNazwa == nazwaSklepu) {
            sklepy.erase(it);
            break;
        }
    }
}

void Firma::wyswietlSklep(int i) {
    std::cout << "Nazwa: " << sklepy[i]->getNazwa() << ", Rodzaj: " << sklepy[i]->getRodzaj() << ", Wielkosc: " << sklepy[i]->getWielkosc() << "\n";
    std::cout << "Godziny otwarcia: " << sklepy[i]->getGodzinyOtwarcia() << ", Budynek: \n";
    sklepy[i]->printBudynek();
}

void Firma::ustawSklep(int i, std::string nazwaSklepu, std::string rodzajSklepu, std::string wielkoscSklepu, std::string godzinyOtwarciaSklepu, Budynek * budynekSklepu) {
    Sklep * sklep = new Sklep(nazwaSklepu, rodzajSklepu, wielkoscSklepu, godzinyOtwarciaSklepu, budynekSklepu);
    sklepy[i] = sklep;
}
