//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Lab 05c
//  @ File Name : Sklep.h
//  @ Date : 30.03.2023
//  @ Author : Tomasz Wnuk
//
//


#if !defined(_SKLEP_H)
#define _SKLEP_H

#include "Budynek.h"

class Sklep {
public:
	void setNazwa(std::string nazwa);
	void setRodzaj(std::string rodzaj);
	void setWielkosc(std::string wielkosc);
	void setGodzinyOtwarcia(std::string godzinyOtwarcia);
	void setBudynek(std::string adresBudynku, int iloscKasBudynku, int wielkoscBudynku, bool klimatyzowanyBudynek, float kosztUtrzymaniaBudynku);
    std::string getNazwa();
    std::string getRodzaj();
    std::string getWielkosc();
    std::string getGodzinyOtwarcia();
	void printBudynek();
	Sklep(std::string nazwa, std::string rodzaj, std::string wielkosc, std::string godzinyOtwarcia, Budynek * budynek);
	~Sklep();
	void printSklep();
	void zareklamujSklep();
	void printGodzinyOtwarcia();
private:
    std::string nazwa;
    std::string rodzaj;
    std::string wielkosc;
    std::string godzinyOtwarcia;
	Budynek * budynek;
};

#endif  //_SKLEP_H
