//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laboratorium 08b
//  @ File Name : A.cpp
//  @ Date : 31.05.2023
//  @ Author : Tomasz Wnuk
//
//

#include "A.h"

void A::fooA() {
    while (n < 10) {
        b->fooB();
        n++;
    }
}
